student:
  arch: vit_small
  patch_size: 14
crops:
  global_crops_size: 518
  local_crops_size: 98
train:
  datasets:
    - dataset_name: CheX_Dataset
      imgpath: /data/vision/cxr/chexpert
      views: ['PA', 'AP']
      csvpath: /data/vision/cxr/chexpert/train.csv # ~ 191,010 samples
      unique_patients: False
      hist_equalize: True
      uncertain_labels_method: U-ONES
      transform:
        - torchvision.transforms.Grayscale(num_output_channels=3) # make it RGB
      pathologies:
        - Atelectasis
        - Cardiomegaly
        - Consolidation
        - Edema
        - Pleural Effusion
val:
  datasets:
    - dataset_name: CheX_Dataset
      imgpath: /data/vision/cxr/chexpert
      views: ['PA', 'AP']
      csvpath: /data/vision/cxr/chexpert/valid.csv
      unique_patients: False
      hist_equalize: True
      transform:
        - torchvision.transforms.Grayscale(num_output_channels=3) # make it RGB
      pathologies:
        - Atelectasis
        - Cardiomegaly
        - Consolidation
        - Edema
        - Pleural Effusion
test:
  datasets:
    - dataset_name: CheX_Test_Dataset
      imgpath: /data/vision/cxr/chexpert/CheXpert-v1.0
      views: ['Frontal']
      csvpath: /data/vision/cxr/chexpert/test_labels.csv
      unique_patients: False
      hist_equalize: True
      transform:
        - torchvision.transforms.Grayscale(num_output_channels=3) # make it RGB
      pathologies:
        - Atelectasis
        - Cardiomegaly
        - Consolidation
        - Edema
        - Pleural Effusion
datasets:
  - dataset_name: CheX_Test_Dataset
    imgpath: /data/vision/cxr/chexpert/CheXpert-v1.0
    views: ['Frontal']
    csvpath: /data/vision/cxr/chexpert/test_labels.csv
    unique_patients: False
    hist_equalize: True
    transform:
      - torchvision.transforms.Grayscale(num_output_channels=3) # make it RGB
    pathologies:
      - Atelectasis
      - Cardiomegaly
      - Consolidation
      - Edema
      - Pleural Effusion