student:
  arch: vit_base
  patch_size: 14
  num_register_tokens: 4
crops:
  global_crops_size: 518
  local_crops_size: 98
train:
  datasets:
    - dataset_name: NIH_Dataset
      csvpath: /data/vision/cxr/cxr8/Data_Entry_2017_v2020_TRAIN.csv
      imgpath: /data/vision/cxr/cxr8/images_jpegs/
      views: ['PA', 'AP']
      unique_patients: False
      hist_equalize: True
      pathologies:
        - Atelectasis
        - Cardiomegaly
        - Effusion
        - Infiltration
        - Mass
        - Nodule
        - Pneumonia
        - Pneumothorax
      transform:
        - torchvision.transforms.Grayscale(num_output_channels=3)   
val:
  datasets:
    - dataset_name: NIH_Dataset
      csvpath: /data/vision/cxr/cxr8/Data_Entry_2017_v2020_VAL.csv
      imgpath: /data/vision/cxr/cxr8/images_jpegs/
      views: ['PA', 'AP']
      unique_patients: False
      hist_equalize: True
      pathologies:
        - Atelectasis
        - Cardiomegaly
        - Effusion
        - Infiltration
        - Mass
        - Nodule
        - Pneumonia
        - Pneumothorax
      transform:
        - torchvision.transforms.Grayscale(num_output_channels=3)   
test:
  datasets:
    - dataset_name: NIH_Dataset
      csvpath: /data/vision/cxr/cxr8/Data_Entry_2017_v2020_TEST.csv
      imgpath: /data/vision/cxr/cxr8/images_jpegs/
      views: ['PA', 'AP']
      unique_patients: False
      hist_equalize: True
      pathologies:
        - Atelectasis
        - Cardiomegaly
        - Effusion
        - Infiltration
        - Mass
        - Nodule
        - Pneumonia
        - Pneumothorax
      transform:
        - torchvision.transforms.Grayscale(num_output_channels=3)   

datasets:
  - dataset_name: NIH_Dataset
    csvpath: /data/vision/cxr/cxr8/Data_Entry_2017_v2020_TEST.csv
    imgpath: /data/vision/cxr/cxr8/images_jpegs/
    views: ['PA', 'AP']
    unique_patients: False
    hist_equalize: True
    pathologies:
      - Atelectasis
      - Cardiomegaly
      - Effusion
      - Infiltration
      - Mass
      - Nodule
      - Pneumonia
      - Pneumothorax
    transform:
      - torchvision.transforms.Grayscale(num_output_channels=3)   