student:
  arch: vit_base
  patch_size: 32
crops:
  global_crops_size: 224
  local_crops_size: 98
train:
  datasets:
    - dataset_name: RSNA_Pneumonia_Dataset
      csvpath: /data/vision/cxr/rsna-pneumonia/unofficial_splits/stage_2_train_labels_TRAIN.csv
      dicomcsvpath: /data/vision/cxr/rsna-pneumonia/stage_2_train_images_dicom_headers.csv
      imgpath: /data/vision/cxr/rsna-pneumonia/stage_2_train_images_jpegs
      views:
        - PA
        - AP
      hist_equalize: False
      transform:
        - torchvision.transforms.Grayscale(num_output_channels=3)   
val:
  datasets:
    - dataset_name: RSNA_Pneumonia_Dataset
      csvpath: /data/vision/cxr/rsna-pneumonia/unofficial_splits/stage_2_train_labels_VAL.csv
      dicomcsvpath: /data/vision/cxr/rsna-pneumonia/stage_2_train_images_dicom_headers.csv
      imgpath: /data/vision/cxr/rsna-pneumonia/stage_2_train_images_jpegs
      views:
        - PA
        - AP
      hist_equalize: False
      transform:
        - torchvision.transforms.Grayscale(num_output_channels=3)   
test:
  datasets:
    - dataset_name: RSNA_Pneumonia_Dataset
      csvpath: /data/vision/cxr/rsna-pneumonia/stage_2_test_labels.csv
      dicomcsvpath: /data/vision/cxr/rsna-pneumonia/stage_2_test_images_dicom_headers.csv
      imgpath: /data/vision/cxr/rsna-pneumonia/stage_2_test_images_jpegs
      views:
        - PA
        - AP
      hist_equalize: False
      transform:
        - torchvision.transforms.Grayscale(num_output_channels=3)   