student:
  arch: vit_base
  patch_size: 16
crops:
  global_crops_size: 224
  local_crops_size: 98
train:
  datasets:
    - dataset_name: "MIMIC_Segmentation_CheXmask"
      imgpath: /data/vision/cxr/mimic-cxr-jpg/2.0.0/files
      mimic_meta_csv: /data/vision/cxr/mimic-cxr-jpg/2.0.0/train_mimic-cxr-2.0.0-metadata.csv.gz # SAMPLE OF 2000 ONLY!
      chexmask_csv: /data/vision/cxr/chexmask-cxr-segmentation-data/0.4/OriginalResolution/MIMIC-CXR-JPG.csv
      hist_equalize: True
      albumentations_transform:
      - A.SmallestMaxSize(max_size=224, interpolation=cv2.INTER_CUBIC)
      - A.CenterCrop(height=224, width=224)
      - A.Affine(scale=(0.75,1.25),translate_percent=(0.1,0.1), rotate=(-10,10), shear=None, p=0.5)
      - A.ElasticTransform(alpha=1, sigma=10, interpolation=cv2.INTER_CUBIC, p=0.5)
      - A.ColorJitter(brightness=(0.8, 1.2), contrast=(0.8, 1.2), saturation=(0.8, 1.2), hue=(-0.5, 0.5), always_apply=None, p=0.5)
      - A.Normalize(mean=(0.48145466, 0.4578275, 0.40821073), std=(0.26862954, 0.26130258, 0.27577711))
      - ToTensorV2()
val:
  datasets:
    - dataset_name: "MIMIC_Segmentation_CheXmask"
      imgpath: /data/vision/cxr/mimic-cxr-jpg/2.0.0/files
      mimic_meta_csv: /data/vision/cxr/mimic-cxr-jpg/2.0.0/valid_mimic-cxr-2.0.0-metadata.csv.gz
      chexmask_csv: /data/vision/cxr/chexmask-cxr-segmentation-data/0.4/OriginalResolution/MIMIC-CXR-JPG.csv
      hist_equalize: True
      albumentations_transform:
      - A.SmallestMaxSize(max_size=224, interpolation=cv2.INTER_CUBIC)
      - A.CenterCrop(height=224, width=224)
      - A.Normalize(mean=(0.48145466, 0.4578275, 0.40821073), std=(0.26862954, 0.26130258, 0.27577711))
      - ToTensorV2()
test:
  datasets:
    - dataset_name: "MIMIC_Segmentation_CheXmask"
      imgpath: /data/vision/cxr/mimic-cxr-jpg/2.0.0/files
      hist_equalize: True
      mimic_meta_csv: /data/vision/cxr/mimic-cxr-jpg/2.0.0/test_mimic-cxr-2.0.0-metadata.csv.gz
      chexmask_csv: /data/vision/cxr/chexmask-cxr-segmentation-data/0.4/OriginalResolution/MIMIC-CXR-JPG.csv
      albumentations_transform:
      - A.SmallestMaxSize(max_size=224, interpolation=cv2.INTER_CUBIC)
      - A.CenterCrop(height=224, width=224)
      - A.Normalize(mean=(0.48145466, 0.4578275, 0.40821073), std=(0.26862954, 0.26130258, 0.27577711))
      - ToTensorV2()